version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: packages/app/Dockerfile
    container_name: chaos-monkey_app
    restart: unless-stopped
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "10074:3000"

  crons:
    build:
      context: ..
      dockerfile: packages/app/crons/Dockerfile
    container_name: chaos-monkey_crons
    restart: unless-stopped
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  db:
    image: postgres:latest
    container_name: chaos-monkey_db
    restart: unless-stopped
    networks:
      - default
    volumes:
      - chaos-monkey-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  redis:
    restart: unless-stopped
    container_name: chaos-monkey_redis
    image: redis:latest
    networks:
      - default
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - chaos-monkey-redis-data:/data

volumes:
  chaos-monkey-postgres-data:
  chaos-monkey-redis-data:

networks:
  default:
    driver: bridge
