version: "3.8"

services:
  app:
    build:
      context: ../packages/app
      dockerfile: Dockerfile
    container_name: chaos-monkey_app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "10074:3000"

  crons:
    build:
      context: ../packages/app
      dockerfile: Dockerfile
    container_name: chaos-monkey_crons
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  db:
    image: postgres:latest
    container_name: chaos-monkey_db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  redis:
    restart: unless-stopped
    container_name: chaos-monkey_redis
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
